### ISSUE TITLE
Class 'BinaryTorch\LaRecipe\LaRecipe' not found 

### ISSUE THREAD

**Issue by marvinhosea** [saleem-hadad/larecipe-feedback#1]
In AssetServiceProvider.php line 27:
                                                   
  Class 'BinaryTorch\LaRecipe\LaRecipe' not found 
Laravel 5.7

**Comment by saleem-hadad** [comment]
make sure you installed [Larecipe](https://github.com/saleem-hadad/larecipe) first, have you done that?

**Comment by marvinhosea** [comment]
Noted
